repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Use the version matching your project
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        files: \.[jt]sx?$
        entry: pnpm run lint
        pass_filenames: false

      - id: typescript-check
        name: typescript-check
        entry: pnpm exec tsc --noEmit
        language: system
        types: [ts, tsx]
        pass_filenames: false

      - id: pnpm-e2e
        name: pnpm-e2e
        entry: pnpm run e2e
        language: system
        stages: [pre-push]
        pass_filenames: false

      # Skip unit test since there is none atm
      # - id: unit-test
      #   name: unit-test
      #   entry: pnpm test
      #   language: system
      #   stages: [pre-push]
      #   pass_filenames: false
