repos:
  - repo: local
    hooks:
      - id: run-web-hooks
        name: Web pre-commit
        files: ^client/
        entry: bash -c 'cd client && pnpm run precommit run'
        language: system
        stages: [pre-push]

      - id: run-server-hooks
        name: Server pre-commit
        files: ^server/
        entry: bash -c 'cd server && pnpm run precommit run'
        language: system
        stages: [pre-push]
